export default {
  // get
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  // add
  ADD_TO_CART_REQUEST: "ADD_TO_CART",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
  // delete
  REMOVE_FROM_CART_REQUEST: "REMOVE_FROM_CART_REQUEST",
  REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR"
};
